# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_spare_part.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5.QtWidgets import QMessageBox

from sql import Ital_Session,  Machine
from PyQt5 import QtCore,  QtWidgets
import traceback


class Ui_add_model_QWidget(object):
    def setupUi(self, add_spare_part_QWidget):
        add_spare_part_QWidget.setObjectName("add_spare_part_QWidget")
        add_spare_part_QWidget.resize(330, 350)
        self.gridLayout = QtWidgets.QGridLayout(add_spare_part_QWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.machine_label = QtWidgets.QLabel(add_spare_part_QWidget)
        self.machine_label.setStyleSheet("font: 10pt;")
        self.machine_label.setObjectName("machine_label")
        self.gridLayout.addWidget(self.machine_label, 0, 0, 1, 1)

        self.machine_lineEdit = QtWidgets.QLineEdit(add_spare_part_QWidget)
        self.machine_lineEdit.setStyleSheet("font: 10pt; ")
        self.machine_lineEdit.setText("")
        self.machine_lineEdit.setObjectName("info_code_lineEdit")
        self.gridLayout.addWidget(self.machine_lineEdit, 0, 1, 1, 1)

        self.save_btn = QtWidgets.QPushButton(add_spare_part_QWidget)
        self.save_btn.setMinimumSize(QtCore.QSize(0, 35))
        self.save_btn.setStyleSheet("background-color: rgb(0, 170, 0); color: rgb(255, 255, 255); font: 10pt;")
        self.save_btn.setObjectName("save_btn")
        self.save_btn.clicked.connect(lambda: self.add_spare_part())
        self.gridLayout.addWidget(self.save_btn, 1, 1, 2, 2)

        self.retranslateUi(add_spare_part_QWidget)
        QtCore.QMetaObject.connectSlotsByName(add_spare_part_QWidget)

    def retranslateUi(self, add_spare_part_QWidget):
        _translate = QtCore.QCoreApplication.translate
        add_spare_part_QWidget.setWindowTitle(_translate("add_spare_part_QWidget", "Προσθήκη Μηχανήματος"))
        self.machine_label.setText(_translate("add_spare_part_QWidget", "Μηχάνημα-Μοντέλο"))

        self.save_btn.setText(_translate("add_spare_part_QWidget", "Αποθήκευση"))

    def add_spare_part(self):
        new_machine = self.machine_lineEdit.text()
        print("new_machine.lower().strip()", new_machine.lower().replace(" ", ""))
        try:
            all_machines_obj = Ital_Session.query(Machine).all()
            for machine in all_machines_obj:
                if str(machine.model).lower().replace(" ", "") == new_machine.lower().replace(" ", ""):
                    print("str(machine.model).lower().strip()", str(machine.model).lower().replace(" ", ""))
                    msgBox = QMessageBox.critical(None, "Σφάλμα", f"To {machine} υπάρχει")
                    return

            new_machine_model = Machine(model=new_machine)

        except Exception:
            msgBox = QMessageBox.critical(None, "Σφάλμα", f"{traceback.print_exc()}")
            print(traceback.print_exc())

        Ital_Session.add(new_machine_model)
        Ital_Session.commit()
        msgBox = QMessageBox.information(None, "Πληροφορία", f"Το μοντέλο αποθηκεύτηκε!")
        return


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setStyle("Fusion")
    app.setStyleSheet("QPushButton {max-height: 40px; min-width: 300px;"
                      "border-top-right-radius: 20px; border-bottom-left-radius: 20px; background-color: #ff9800;}"
                      "QPushButton:enabled { background-color: #55aa7f; color: white; }")
    add_spare_part_QWidget = QtWidgets.QWidget()
    ui = Ui_add_spare_part_QWidget()
    ui.setupUi(add_spare_part_QWidget)
    add_spare_part_QWidget.show()
    sys.exit(app.exec_())
